import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:hive_flutter/hive_flutter.dart';
import 'package:appflowy_editor/appflowy_editor.dart';
import 'stores/auth_store.dart';
import 'ui/screens/main_layout.dart';
import 'ui/screens/vault_entry_screen.dart';
import 'ui/components/command_palette.dart';
import 'utils/logger.dart';
import 'package:universal_html/html.dart' as html;
import 'package:flutter/foundation.dart';
import 'firebase_options.dart'; // Generated by FlutterFire CLI
import 'package:firebase_core/firebase_core.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Hive.initFlutter();

// Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  FlutterError.onError = (FlutterErrorDetails details) {
    final exception = details.exception;
    final stack = details.stack;

    // Log the REAL exception (not the _trace error)
    KragLogger.info(LogDomain.general,
        '>>> ORIGINAL EXCEPTION: ${exception.runtimeType}: $exception <<<');
    KragLogger.info(LogDomain.general, '>>> STACK TRACE:\n$stack');

    // Optional: send to your logger
    KragLogger.error(
        LogDomain.general, '>>> Flutter Error <<<', exception, stack);

    // Still show in console
    FlutterError.dumpErrorToConsole(details);
  };

  if (kIsWeb) {
    html.window.onError.listen((error) {
      KragLogger.error(LogDomain.general, '>>> JS Exception <<<', error);
    });
  }
  runApp(
    const ProviderScope(
      child: KragApp(),
    ),
  );
}

class KragApp extends ConsumerWidget {
  const KragApp({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final authState = ref.watch(authStoreProvider);

    return MaterialApp(
      title: 'Krag',
      debugShowCheckedModeBanner: false,
      localizationsDelegates: const [
        AppFlowyEditorLocalizations.delegate,
      ],
      supportedLocales: AppFlowyEditorLocalizations.delegate.supportedLocales,
      theme: ThemeData(
        useMaterial3: true,
        colorScheme: const ColorScheme.dark(
          primary: Color(0xFFFF6B00),
          surface: Color(0xFF1E1E1E),
          onSurface: Color(0xFFEDEDED),
          secondary: Color(0xFFA0A0A0),
        ),
        scaffoldBackgroundColor: const Color(0xFF121212),
        fontFamily: 'Inter',
        inputDecorationTheme: InputDecorationTheme(
          filled: true,
          fillColor: const Color(0xFF121212),
          border: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFF3A3A3A)),
          ),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFF3A3A3A)),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(8),
            borderSide: const BorderSide(color: Color(0xFFFF6B00)),
          ),
        ),
      ),
      home: CommandPaletteListener(
        child: _buildHome(authState),
      ),
    );
  }

  Widget _buildHome(AuthState authState) {
    if (authState.isLoading) {
      return const Scaffold(
        body: Center(
          child: CircularProgressIndicator(color: Color(0xFFFF6B00)),
        ),
      );
    }

    if (authState.isAuthenticated) {
      return const MainLayout();
    }

    return const VaultEntryScreen();
  }
}
